/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        paper: 'var(--color-paper)',
        cream: 'var(--color-cream)',
        ink: 'var(--color-ink)',
        'ink-soft': 'var(--color-ink-soft)',
        hairline: 'var(--color-hairline)',
        maroon: 'var(--color-maroon)',
        terracotta: 'var(--color-terracotta)',
        'thread-green': 'var(--color-thread-green)',
        indigo: 'var(--color-indigo)',
        saffron: 'var(--color-saffron)',
        'zari-gold': 'var(--color-zari-gold)',
        kasoori: 'var(--phulkari-kasoori)',
        gulabi: 'var(--phulkari-gulabi)',
        neela: 'var(--phulkari-neela)',
        hara: 'var(--phulkari-hara)',
        sunehri: 'var(--phulkari-sunehri)',
        laal: 'var(--phulkari-laal)',
        'band-viah': 'var(--band-viah)',
        'band-suhaag': 'var(--band-suhaag)',
        'band-trinjan': 'var(--band-trinjan)',
        'band-bhaiya': 'var(--band-bhaiya)',
        'maroon-40': 'rgba(125,41,34,0.4)',
        'maroon-50': 'rgba(125,41,34,0.5)',
        'maroon-60': 'rgba(125,41,34,0.6)',
        'gold-60': 'rgba(201,162,39,0.6)',
        'gold-70': 'rgba(201,162,39,0.7)',
        'paper-90': 'rgba(244,239,229,0.9)',
        'paper-95': 'rgba(244,239,229,0.95)',
      },
      fontFamily: {
        serif: ['"Noto Serif"', 'Georgia', 'serif'],
        sans: ['"Noto Sans"', 'system-ui', 'sans-serif'],
        gurmukhi: ['"Noto Sans Gurmukhi"', '"Noto Sans"', 'sans-serif'],
        'gurmukhi-serif': ['"Noto Serif Gurmukhi"', '"Noto Serif"', 'serif'],
      },
      maxWidth: { site: '80rem' },
      borderRadius: {
        none: '0px',
        xs: '2px',
        sm: '3px',
        DEFAULT: '2px',
        md: '4px',
        lg: '6px',
        xl: '10px',
        '2xl': '14px',
        '3xl': '18px',
        full: '9999px',
      },
      transitionDuration: {
        DEFAULT: '250ms',
        '100': '100ms',
        '150': '150ms',
        '200': '200ms',
        '250': '250ms',
        '300': '300ms',
        '400': '400ms',
        '500': '500ms',
        '700': '700ms',
        '1000': '1000ms',
      },
      transitionTimingFunction: {
        DEFAULT: 'cubic-bezier(0.33, 1, 0.68, 1)',
        'out-expo': 'cubic-bezier(0.16, 1, 0.3, 1)',
        'in-out-quart': 'cubic-bezier(0.76, 0, 0.24, 1)',
      },
    },
  },
  plugins: [],
};
